### ISSUE TITLE
Brew Installation or Upgrade Fails when docker is not running

### ISSUE THREAD

**Issue by navarr** [swiftotter/den#100]
**Version of Homebrew**
```
Homebrew 3.6.5
Homebrew/homebrew-core (git revision a4f853c3c86; last commit 2022-10-14)
Homebrew/homebrew-cask (git revision 4b6243dcf7; last commit 2022-10-15)
```

**Operating System**
Mac OS 12.6

**Describe the bug**
Caused by swiftotter/homebrew-den#2, initially reported at https://github.com/swiftotter/homebrew-den/pull/2#issuecomment-1280450726

> today I tried to run `brew upgrade` while my Docker Desktop wasn't running yet (pretty OK situation if you're on MacOS). 
And it failed to update den.
> <img width="967" alt="image" src="https://user-images.githubusercontent.com/1873745/196122060-c85eb97a-6bbc-4b51-93a0-f6c836af4b75.png">
> Maybe we should move this logic to https://github.com/swiftotter/den/blob/main/commands/install.cmd#L2 ?

**To Reproduce**
1. Ensure Docker is not running
2. Run `brew upgrade swiftotter/den/den`

**Expected behavior**
Den upgrades without any errors

**Screenshots**
<img width="967" alt="image" src="https://user-images.githubusercontent.com/1873745/196122060-c85eb97a-6bbc-4b51-93a0-f6c836af4b75.png">

**Comment by bap14** [comment]
@navarr I think i have a solution in mind for this. Let me know your thoughts.

- Remove the build image logic from the Homebrew post-install
- Add a file indicator / flag to `$WARDEN_HOME_DIR` during post-install and/or during `den install` run
- During `den svc up` check for the existence of the flag, and if it's found rebuild the dashboard and restart the dashboard (or alternatively rebuild the image and then allow all other services to start), then delete the flag

**Comment by ihor-sviziev** [comment]
> Add a file indicator / flag to $WARDEN_HOME_DIR during post-install and/or during den install run

We already have it in 
https://github.com/swiftotter/den/blob/2d9127d178678940f367beaf9f678515bf8ffe0e/commands/svc.cmd#L5
https://github.com/swiftotter/den/blob/d4166030b684140a23723c26f193620bc962b875/utils/install.sh#L33-L35

**Comment by bap14** [comment]
@ihor-sviziev I had brought up mounting the version file into Nginx, and it wouldn't work because the version file is outside the home directory by default. I had thought of using the installed text file, but for some reason decided against it, possibly because once the update is done there's nothing forcing the user to restart the den service.

I'll take a look at moving it to a docker-entrypoint script, see if that will work. It would be cleaner that way across brew and manual installations as well.

**Comment by bap14** [comment]
@ihor-sviziev @navarr I submitted https://github.com/swiftotter/den/pull/104 which will allow removing the image rebuild from the Homebrew process. It shifts it to reading the version file into an environment variable, and passing that to the `docker compose` command which passes it to the image.

So now we can build a "static" image instead of requiring the image be built by each user individually, and the version can still change.

I gave this a simple test running outside of my home directory in `/opt/den` and a simple update to the version file and `den svc restart` caused the file to be updated.

**Comment by navarr** [comment]
Brew Upgrade still fails if Docker isn't running.

```
navarr@Navarrs-MBP-2 znd-cloud % brew upgrade swiftotter/den/den
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 4 taps (homebrew/core, homebrew/cask, homebrew/cask-drivers and swiftotter/den).
==> New Formulae
postgresql@15
==> New Casks
eloquent                        genesis-plus                    prismlauncher                   sms-plus                        topaz-denoise-ai                topaz-gigapixel-ai              topaz-sharpen-ai                topaz-video-ai

You have 50 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Upgrading 1 outdated package:
swiftotter/den/den 1.0.0-beta.10 -> 1.0.0-beta.11
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
den: Docker with Docker Compose >= 2.2.3 is required for Den. Please install Docker Desktop via brew with 'brew install --cask docker', download it from https://docker.com/ or use your system package manager to install Docker Engine >= 20.10.16
Error: den: An unsatisfied requirement failed this build.


navarr@Navarrs-MBP-2 znd-cloud % docker version --format '{{.Server.Version}}'
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

navarr@Navarrs-MBP-2 znd-cloud % docker version
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Client:
 Cloud integration: v1.0.29
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:20:35 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true
```

**Comment by bap14** [comment]
@navarr Ah, that's a part of the docker requirement check. Since docker can be installed in a number of ways, it tries to get the current version of Docker. If Docker isn't running it fails.

I can adjust it so that there's a check for if docker is running first, before checking for version. This way if docker is running it ensures proper versions, and if it's not running, it just assumes the correct version.

Sound like a reasonable solution?

**Comment by bap14** [comment]
@navarr Addressed in https://github.com/swiftotter/homebrew-den/pull/6

**Comment by navarr** [comment]
Thanks, @bap14!
