### ISSUE TITLE
Basic shell friendlyness

### ISSUE THREAD

**Issue by DavidLambauer** [swiftotter/den#101]
Heya,

would it be possible to allow some very common shell aliases? E.g. `ll` instead of `ls -haltr...` or `..` for `cd ..`. Or is there a simple way of adding those myself?

**Comment by DavidLambauer** [comment]
A proper history would also be super lovely. I don't know what you think about these kinds of developer experience features in general, but I personally would love to see a zsh in there.

**Comment by mautz-et-tong** [comment]
history should be there (at least it is configured `HISTFILE: /bash_history/.bash_history`)
+1 for zsh. I can help with plugins and settings

**Comment by sprankhub** [comment]
I actually thought about asking for more advanced shells :D So if you wish for them anyway: I would prefer fish shell!

**Comment by DavidLambauer** [comment]
hehehe I knew this discussion would pop up whether zsh or fish or any other. Is it possible to introduce a setting for your preferred shell? Similar to the composer setting where you can choose between the versions?!

**Comment by sprankhub** [comment]
Of course :joy: 

A setting would be awesome!

**Comment by navarr** [comment]
You can always mount a bash profile into your container.  You can even do this for all projects by creating `~/.den/environments/includes/php-fpm.base.yml` which'll be merged during `den env` calls (including `den shell`).

I'm personally not super familiar with improvements in zsh over bash.  I'm unsure if simply installing `zsh` is really the overall solution, since that doesn't seem to add any niceties by itself, as far as I can tell. 

More than happy to learn more, however.

**Comment by bap14** [comment]
I would say that the Den project itself should stick with the "barebones" images. Those who wish to use a different shell can extend the image to add the shell and set it as the default shell. Due to the number of BaSH alternatives we'd have to select a limited list of shells to install, which inevitably will upset someone.

In my opinion it would be better to just extend and build your own images and publish them. We could add a list of alternative image repositories that are available via the Den community (e.g. Debian-based images, Zsh/Ksh/Fish/Dash/Xonsh/Nushell).

**Comment by DavidLambauer** [comment]
Picking a different shell is biased, but either would be better than what we have right now. I know @sprankhub already mentioned fish but based on popularity, it makes sense to pick zsh. 

I think the real benefit of den is that we **don't** have to deal with building our images. den is made not to have to deal with this and is also focused on developer experience. Therefore, I can see zsh built in.

**Comment by mautz-et-tong** [comment]
I can create a test container based on the php-fpm container with fish and zsh including some improvements as a basis for discussions

**Comment by bap14** [comment]
@DavidLambauer @sprankhub 
Out of curiosity, what workflows and tasks are you doing directly in the shell that having a different shell other than BaSH will make things easier?

**Comment by sprankhub** [comment]
For me, it is pretty much these:

    composer install
    composer update [...]
    composer require [...]
    setup:upgrade
    index:reindex
    sys:cron:run
    [many more n98-magerun commands]

Fish just makes it incredibly easy to go through old commands and execute them again. It has a very smart auto-completion. Plus, I use it on my host machine, so it would just be handy to have the same in the container to not have to think of another shell there. It is just nice to have and I do not see a real disadvantage as long as it is configurable :thinking:

**Comment by bap14** [comment]
@sprankhub  The shell to use is already configurable; however, the shells just aren't installed. For example: `WARDEN_ENV_SHELL_COMMAND=ash den shell` will drop me into an ash shell, instead of the default BaSH.

I built a quick php-fpm image and added Fish and it appears to install into `/usr/bin` instead of `/bin` so if we add fish as a shell, either you'd have to specify `/usr/bin/fish` as the warden env shell command, or we'd have to add some logic in the `den shell` command to set the proper path to the shell (or use `/usr/bin/env <shell>` as the shell command).

That wouldn't help with things like shortcuts and aliases from your own `.<shell>rc` file though.

**Comment by bap14** [comment]
Created PR https://github.com/swiftotter/den/pull/107 which gives Fish and Zsh. Also adds the ability to set a "default shell" at the user (`~/.den/.env`), project (`${WARDEN_ENV_DIR}/.env`) and one-off command (`USE_SHELL=fish den shell`) levels.

For the one-off command shell change, it has to be done this way because otherwise the user and project configs (if set) would override it. This way there's a unique flag to override those. And everything defaults to BaSH. I also updated the documentation to reflect the available shells.

**Comment by bap14** [comment]
While I created the PR, I still feel like extending the Den base images for your own images is the proper way to go. Perhaps as a community we could create a list of available alternative images that follow the Den naming conventions. This way you as a developer could say "I want feature X, and sprankhub has that built into his images, I'll just use his registry instead of Den's". Then it's just a matter of editing your `WARDEN_IMAGE_REPOSITORY` value from the default `ghcr.io/swiftotter` to `ghcr.io/sprankhub` to use their Den image variants.

This is something Den already supports, so would be really easy to implement. The downside is that it somewhat fractures the community that's forming around Den and its images, and risks those who started image forks stopping support.

@navarr @DavidLambauer @sprankhub

**Comment by navarr** [comment]
Having repositories like that causes issues if they don't rebuild regularly. It's easy to get out of sync that way

A custom Dockerfile in the project is best. I might merge the PR though so it can be user choice without having to add it to every project and every developer having to rebuild images

**Comment by navarr** [comment]
HI all, following up on this.

This ticket's actual description is pretty vague on what is desired to approve/close it.

Can we nail down something specific, or shall we convert it to a discussion?

**Comment by DavidLambauer** [comment]
I'd say, just close it...
