### ISSUE TITLE
Varnish images are too heavy

### ISSUE THREAD

**Issue by ihor-sviziev** [swiftotter/den#38]
Hi,
I just noticed that varnish images are bigger (both compressed and uncompressed) than the m2 PHP-fpm images with node.
<img width="766" alt="image" src="https://user-images.githubusercontent.com/1873745/187638548-def24c39-6fff-4a48-bad1-1398b0df549d.png">

I did inspect the image size using the following script:
```
dockersize() { docker manifest inspect -v "$1" | jq -c 'if type == "array" then .[] else . end' |  jq -r '[ ( .Descriptor.platform | [ .os, .architecture, .variant, ."os.version" ] | del(..|nulls) | join("/") ), ( [ .SchemaV2Manifest.layers[].size ] | add ) ] | join(" ")' | numfmt --to iec --format '%.2f' --field 2 | column -t ; }
```
Then compared to the [official varnish images](https://hub.docker.com/_/varnish) and to php-fpm images:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/1873745/187639690-ecdc7613-5dca-453f-b65f-88a644a4870d.png">

**Comment by navarr** [comment]
Thanks for this report!  These are currently unchanged from Warden.  (Since they were arm64 compatible I didn't take a second glance!)

Looks like its building them out on top of Centos Stream8

What would need updating as part of this ticket:

* `/images/varnish/Dockerfile`
* _possibly_ `images/varnish/default.vcl`
